//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParexasAnxo.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParexasAnxo.RecursosLocalizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anónimo.
        /// </summary>
        internal static string anonimo {
            get {
                return ResourceManager.GetString("anonimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anxo Pregal.
        /// </summary>
        internal static string autor {
            get {
                return ResourceManager.GetString("autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso 16/17.
        /// </summary>
        internal static string curso {
            get {
                return ResourceManager.GetString("curso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desexas xogar outra partida?.
        /// </summary>
        internal static string desexas {
            get {
                return ResourceManager.GetString("desexas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feito por:.
        /// </summary>
        internal static string feitopor {
            get {
                return ResourceManager.GetString("feitopor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIN DO XOGO MEU.
        /// </summary>
        internal static string fin {
            get {
                return ResourceManager.GetString("fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información do autor.
        /// </summary>
        internal static string infor {
            get {
                return ResourceManager.GetString("infor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxecto DI.
        /// </summary>
        internal static string proxecto {
            get {
                return ResourceManager.GetString("proxecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teu nome:.
        /// </summary>
        internal static string teunome {
            get {
                return ResourceManager.GetString("teunome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TI GAÑAS!!.
        /// </summary>
        internal static string tiganas {
            get {
                return ResourceManager.GetString("tiganas", resourceCulture);
            }
        }
    }
}
